name: Check Score

on:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "*/6 * * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Verify Python
      run: python3 --version

    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt

    - name: Check
      run: |
        cd src
        python3 main.py
      env:
        ID: ${{ secrets.ID }}
        PASSWD: ${{ secrets.PASSWD }}
        SID: ${{ secrets.SID }}
        MAIL_ID: ${{ secrets.MAIL_ID }}
        MAIL_PASS: ${{ secrets.MAIL_PASS }}
        NOTIFICATION: ${{ secrets.NOTIFICATION }}
        NOTIFY_SOLUTION: ${{ secrets.NOTIFY_SOLUTION }}
